---
title: "Final"
author: "Sydney Beckett"
format: html
---

https://github.com/sydneymbeckett/ENVS-193DS_spring-2025_final.git 


```{r message= FALSE, warning=FALSE}
library(tidyverse) # general use
library(here) # file organization
library(gt) # creating summary tables
library(flextable) # creating summary tables
library(janitor) # cleaning data frames
library(lubridate) 
sst <- read_csv("data/SST_update2023.csv")
```

## Problem 1.

**a)**

In part 1 they likely used a correlation test because they were comparing two continuous variables.
In part 2 they likely used a one-way ANOVA because they were comparing one continuous variable "between sources", which is more than 2 groups.

**b)**
Another test that could be used is 

**c)**

## Problem 2.

**a)**
```{r}
sst_clean <- sst |> #use the sst data frame
  clean_names() |> #clean up the column names
  mutate(date = ymd(date)) |>  #making sure the date is read as a date
  mutate(
  year = (year(date)), #making the year a date
    month = month(date, label = TRUE, abbr = TRUE)) |> #making the month category and using abbreviations 
  filter(year >= 2018) |>  # only include recent 6 years) 
  group_by(year, month) |> #grouping by year and month
    summarize(
    mean_monthly_sst = round(mean(temp, na.rm = TRUE), 1), #calculate the mean monthly sst and round out to one decimal place
    .groups = "drop" # ungroup after summarize
  ) |> 
    mutate(year = factor(year), #converting to a factor after filtering
      month = factor(month, levels = month.abb, ordered = TRUE)) #ensure correct month ordering

sst_clean |> slice_sample(n = 5) #show 5 first rows

str(sst_clean) #show structure
  

```


